build:
  environment:
    php:
      version: '7.0'
  tests:
      override:
          -
              command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
              coverage:
                  file: 'clover.xml'
                  format: 'clover'
checks:
  php: true
filter:
  excluded_paths:
    - bin/
    - tests/
tools:
  php_code_sniffer: true
  php_mess_detector: true
  php_loc:
    enabled: true
    excluded_dirs: [vendor, tests]
  php_pdepend: true
  php_cpd:
    enabled: true
    excluded_dirs: [vendor, tests]
  sensiolabs_security_checker: true
