build:
  environment:
    php:
      version: '7.0'
  tests:
      override:
          -
              command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
              coverage:
                  file: 'clover.xml'
                  format: 'clover'
checks:
  php: true
filter:
  excluded_paths:
    - bin/
    - tests/
tools:
  php_code_sniffer:
    config:
      standard: PSR2
