language: php

php:
  # using major version aliases
  # aliased to a recent 5.4.x version
  - 5.4
  # aliased to a recent 5.5.x version
  - 5.5
  # aliased to a recent 5.6.x version
  - 5.6

  # Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

  # Commands you want to run that will verify your build.
script: phpunit

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always
