language: php
php:
  - 7.0
  - 7.1
install:
  # Composer
  - composer self-update
  - COMPOSER_ROOT_VERSION=dev-master composer install
script:
  # Code style
  - php vendor/bin/phpcs ./src --standard=PSR1,PSR2 --encoding=utf-8
  # PHPUnit
  - php vendor/bin/phpunit
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b84e6a583d6eea87d0eb
      - https://webhooks.gitter.im/e/c4fa557829c5bd992271
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
