<?="<?php"?>

/**
 * @namespace
 */
namespace Application\<?=$model?>;

use Bluz\Grid\Source\SelectSource;

/**
 * Grid based on Table
 *
 * @package  Application\<?=$model . "\n"?>
 *
 * @author   <?=$author . "\n"?>
 * @created  <?=$date . "\n"?>
 */
class Grid extends \Bluz\Grid\Grid
{
    /**
     * @var string
     */
    protected $uid = '<?=strtolower($model)?>';

    /**
     * @return self
     */
    public function init()
    {
        // Current table as source of grid
        $adapter = new SelectSource();
        $adapter->setSource(Table::select());

        $this->setAdapter($adapter);
        $this->setDefaultLimit(25);
        $this->setAllowOrders([]);

        return $this;
    }
}
