<?="<?php"?>

declare(strict_types=1);

namespace Application\<?=$model?>;

use Bluz\Grid\Source\SelectSource;

/**
 * Grid based on Table
 *
 * @package  Application\<?=$model . "\n"?>
 *
 * @method   Row[] getData()
 *
 * @author   <?=$author . "\n"?>
 * @created  <?=$date . "\n"?>
 */
class Grid extends \Bluz\Grid\Grid
{
    /**
     * @var string
     */
    protected $uid = '<?=strtolower($model)?>';

    /**
     * @return void
     */
    public function init(): void
    {
        // Current table as source of grid
        $adapter = new SelectSource();
        $adapter->setSource(Table::select());

        $this->setAdapter($adapter);
        $this->setDefaultLimit(25);
<?php if (count($columns)) : ?>
        $this->setAllowFilters([
<?php foreach ($columns as $column => $meta) : ?>
            '<?=$column?>',
<?php endforeach; ?>
        ]);
        $this->setAllowOrders([
<?php foreach ($columns as $column => $meta) : ?>
            '<?=$column?>',
<?php endforeach; ?>
        ]);
<?php endif; ?>
    }
}
