<?="<?php"?>

/**
 * @namespace
 */
namespace Application\<?=$model?>;

/**
 * Class Row for `<?=$table?>`
 *
 * @package  Application\<?=$model . "\n"?>
 *
<?=$properties?>
 *
 * @author   <?=$author . "\n"?>
 * @created  <?=$date . "\n"?>
 */
class Row extends \Bluz\Db\Row
{
    /**
     * @return void
     */
    public function beforeInsert()
    {
    }

    /**
     * @return void
     */
    public function beforeUpdate()
    {
    }
}
