<?= '<?php' ?>

declare(strict_types=1);

namespace Application\<?=$model?>;

/**
 * Class Table for `<?=$table?>`
 *
 * @package  Application\<?=$model . "\n"?>
 *
 * @author   <?=$author . "\n"?>
 * @created  <?=$date . "\n"?>
 */
class Table extends \Bluz\Db\Table
{
    /**
     * @var string
     */
    protected $name = '<?=$table?>';

    /**
     * @var string
     */
    protected $rowClass = Row::class;

    /**
     * Primary key(s)
     * @var array
     */
    protected $primary = [<?=$primaryKey?>];
}
