<?="<?php"?>

/**
 * @namespace
 */
namespace Application\<?=$model?>;

/**
 * Class Table for `<?=$table?>`
 *
 * @package  Application\<?=$model . "\n"?>
 *
 * @author   <?=$author . "\n"?>
 * @created  <?=$date . "\n"?>
 */
class Table extends \Bluz\Db\Table
{
    /**
     * @var string
     */
    protected $name = '<?=$table?>';

    protected $rowClass = '\Application\<?=$model?>\Row';

    /**
     * Primary key(s)
     * @var array
     */
    protected $primary = [<?=$primaryKey?>];
}
