<?="<?php"?>

/**
 * Grid controller for <?=$model?> model
 *
 * @author   <?=$author . "\n"?>
 * @created  <?=$date . "\n"?>
 */

/**
 * @namespace
 */
namespace Application;

use Bluz\Controller\Controller;

/**
 * @privilege Management
 *
 * @return mixed
 */
return function () {
    /**
     * @var Controller $this
     */
    $grid = new <?=$model?>\Grid();
    $this->assign('grid', $grid);
};
