<?="<?php\n"?>
/**
 * @var \Bluz\Grid\Grid $grid
 */
if (!$grid) return;
$uid = $grid->getUid();
<?="?>\n"?>
<div class="clearfix" data-spy="grid" data-grid="<?='<?=$uid?>'?>">
  <script>
    // use data-spy="grid" for use AJAX for reload grid
    require(['bluz.grid']);
  </script>

  <nav class="navbar navbar-light bg-light justify-content-between">
    <div>
      <a href="<?="<?=\$this->url('$module', 'crud')?>"?>" class="btn btn-primary"
         data-ajax-dialog data-ajax-method="get" data-modal-style="modal-lg">
          <?= __('Create') ?>
      </a>
      <!-- Place button filters here -->
    </div>
    <!-- Place search form here -->
  </nav>

  <hr/>

  <?="<?=\$this->partial('grid/total.phtml', ['grid'=>\$grid]) ?>\n"?>
  <?="<?=\$this->partial('grid/limit.phtml', ['grid'=>\$grid]) ?>\n"?>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th width="40px"><a href="<?="<?= \$grid->order('id') ?: '#' ?>"?>"><?="<?= __('Id') ?>"?></a></th>
        <th>Header example</th>
        <!-- Place your column headers here, for generate link for order use method $grid->order('column name') -->
        <th width="160px"></th>
      </tr>
    </thead>
    <tbody>
      <?='<?php foreach($grid->getData() as $row) : ?>'?><?="\n"?>
      <tr>
        <td><?="<?=\$row['id']?>"?></td>
        <td>Content example</td>
        <!-- Place your content her, use $row['column name'] -->
        <td class="controls">
          <a href="<?="<?= \$this->url('$module', 'crud', ['id' => \$row['id']]) ?>"?>" class="btn btn-primary"
             data-ajax-dialog data-ajax-method="get" data-modal-style="modal-lg">
            <i class="fa fa-pencil"></i>
          </a>
          <a href="<?="<?= \$this->url('$module', 'crud', ['id' => \$row['id']]) ?>"?>" class="btn btn-danger"
             data-confirm data-ajax data-ajax-method="delete">
            <i class="fa fa-trash-o"></i>
          </a>
        </td>
      </tr>
      <?='<?php endforeach; ?>'?><?="\n"?>
    </tbody>
  </table>

  <?="<?=\$this->partial('grid/empty-rows.phtml', ['grid'=>\$grid]) ?>\n"?>
  <?="<?=\$this->partial('grid/pagination.phtml', ['grid'=>\$grid]) ?>\n"?>
  <?="<?=\$this->partial('grid/total.phtml', ['grid'=>\$grid]) ?>\n"?>

</div>
